# Use Node.js base image
FROM node:18-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy rest of the code
COPY . .

EXPOSE 5000

CMD ["npm", "start"]
